// eslint-disable-next-line
export const config = {
  api: 'api/',
  version: 'v1/',
  apiBase: 'api/v1/',
  refreshTokenExpiry: 3300000, // milliseconds
  logoutTimer: 300, // seconds
  cookieExpiryWarning: 60,
  show: 'show',
  hide: 'hide',
  defaultDateFormat: 'MM-DD-YYYY',
  timeFormat: 'h:mm a',
  defaultDateTimeFormat: 'MM-DD-YYYY h:mm A',
  graphTitleFormat: 'dddd, MM/DD/YYYY',
  phoneFormat: '999 999 9999',
  mobileViewWidth: 768,
  tabletViewWidth: 1024,
  passwordMinLength: 8,
  initialListPageSize: 25,
  listPageSize: 25,
  maxPagesToShow: 5,
  pageSizeOptions: [25, 50, 75, 100],
  maxFileSize: 100000000,
  maxFileSizeMB: 100,
  month: 'mo',
  months: 'mos',
  year: 'yr',
  years: 'yrs',
  weekDays: ["Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "Sat",
  "Sun"],
  completeDays: {
    "Mon": 'Monday',
    "Tue": 'Tuesday',
    "Wed": 'Wednesday',
    "Thu": 'Thursday',
    "Fri": 'Friday',
    "Sat": 'Saturday',
    "Sun": 'Sunday'
  },
};
